version: '3.8'
services:
  img:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: meu-portfolio
    ports:
      - 3000:3000
    volumes:
      - './:/usr/src/app'
    network_mode: bridge
    tty: true
    stdin_open: true